### ISSUE TITLE
Preparación del proxy inverso

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#11]
Preparación del proxy inverso para la derivación hacia los dos sistemas.

**Comment by alvdomnun** [comment]
Actualizadas etiquetas respecto a la nueva organización.

**Comment by miguemiguemigue** [comment]
Tras ponerme en contacto con Roberto (Integración y Arquitectura grupo2), me explica como ha preparado el proxy y se va a seguir su metodología para utilizar un solo proxy escuchando en el puerto 80 del servidor y poder redirigir las peticiones correctamente.
