### ISSUE TITLE
Solución para Gestión de programa y Visualización de programa (WordPress congreso)

### ISSUE THREAD

**Issue by miguemiguemigue** [Proyecto-EGC-G1/Integracion-EGC-G1#23]
Hay que ponerse en contacto con gestión de programa para que confirmen la necesidad de crear ciertas tablas en BBDD de WordPress, que también les son necesarias al grupo de visualización de programas.
De validar la solución, habría que crear un script que creará esas nuevas tablas en el esquema de WordPress.
Entregar dicho script en la carpeta de scripts que ya tenemos en el repositorio.

**Comment by SurielAido** [comment]
Se hizo hablo con Programa, me pidío que crease unas tablas para la BD y me paso el modelo relacional de lo que necesitaba. Lo estudié,  cuando lo vi viable realicé las tabalas y le pasé el Script a él, además de subirlo a github.

**Comment by alvdomnun** [comment]
Verificado por el subgrupo en cuestión, cierro la tarea.

**Comment by miguemiguemigue** [comment]
Hay que añadir al script las claves ajenas entre tablas y renombrarlas para ponerle el prefijo wp_

**Comment by alvdomnun** [comment]
Añadido script, pendiente de verificación.

**Comment by SurielAido** [comment]
Script añadido y verificado con los problemas solucionados.
