### ISSUE TITLE
Solución para cabina Telegram

### ISSUE THREAD

**Issue by miguemiguemigue** [Proyecto-EGC-G1/Integracion-EGC-G1#24]
Hay que aclarar como se va a integrar la cabina de Telegram. Se discutió el problema de registrar nuevos usuarios y autenticarlos mediante Telegram.
Problemas que nos ha indicado el grupo de cabina:
- No hay URI con la que puedan sacar el listado de votaciones (estudiar si es necesario realmente o se les permite acceder directamente a la tabla de votaciones).
- Proponen autenticación con el número de teléfono asociado a la cuenta de Telegram (¿Cómo implementamos esto con el diseño actual? Hablar con registro, porque deben dar visto bueno de la solución.

Registro: Nicolás Luna
Cabina Telegram: José Manuel Lazaro

Nota: La solución aplicada para Telegram, puede reutilizarse para la cabina de Slack. Hablar con ellos también para conocer su enfoque.

**Comment by Ajose4** [comment]
Tras hablar con el coordinador para verificar que seguía en píe su propuesta ha confirmado que sí y se estudió. Pero se ha llegado a la conclusión que sería complicado agregarla a esta altura.

**Comment by Ajose4** [comment]
Después de hablar con el coordinador se le ha solucionado el problema de la URI que solicitaba y por otro lado se ha descartado la propuesta de la autenticación.
