### ISSUE TITLE
Revisar y aprobar los incrementos funcionales propuestos

### ISSUE THREAD

**Issue by miguemiguemigue** [Proyecto-EGC-G1/Integracion-EGC-G1#25]
Los grupos están aportando sus propuestas de incremento funcional. Debemos estudiar si son viables antes de dar el visto bueno, puesto que hay que evaluar el posible impacto en el resto de subsistemas. 
Aceptaremos aquellos incrementos viables e informar a dicho grupo.
Importante estudiarlos conforme aporten su idea, puesto que necesitan empiezar dichos incrementos.
Crear documento sencillo donde pongamos los incrementos aceptados de cada grupo.

Carpeta de las propuestas: https://github.com/Proyecto-EGC-G1/Integracion-EGC-G1/tree/master/Propuestas_incremento_funcional

**Comment by alvdomnun** [comment]
Se cierra la tarea al estar duplicada. Procedo a actualizar la existente.
