### ISSUE TITLE
Aclarar responsabilidades entre almacenamiento de votos y las cabinas

### ISSUE THREAD

**Issue by miguemiguemigue** [Proyecto-EGC-G1/Integracion-EGC-G1#26]
Hay que ponerse en contacto con almacenamiento de votos (que no estuvieron en la última reunión) para que sepan cuál es su función.
Aclarar qué deben hacer exactamente las cabinas (¿sólo lectura?,¿cabinas de Telegram y Slack dan de alta votaciones y usuarios, o solo leen?) y qué debe hacer almacenamiento de votos.
Identificar en todo caso qué métodos debe proveer almacenamiento en forma de API para que las cabinas les manden votos.

**Comment by alvdomnun** [comment]
Añadida también la necesidad de aclarar las responsabilidades entre administración de censos y administración de votaciones. Hay un bloqueo en el que los segundos necesitan ahora una funcionalidad de los primeros y no saben cómo obtenerla antes de integrar los subsistemas.

**Comment by SurielAido** [comment]
Se ha hablado ya con los dos grupos. Aún así sigue habiendo problemas de comprensión con el grupo de almacenamiento de votos. Se está hablando con ellos y se está solucionando.

**Comment by Paula204** [comment]
Solucionado.
