### ISSUE TITLE
Investigación de uso del proxy inverso

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#3]
Investigación sobre el uso del proxy inverso.

**Comment by alvdomnun** [comment]
Cambiadas las prioridades

**Comment by miguemiguemigue** [comment]
Tras ponerme en contacto con Roberto (Integración y Arquitectura grupo2), me explica como ha preparado el proxy y se va a seguir su metodología para utilizar un solo proxy escuchando en el puerto 80 del servidor y poder redirigir las peticiones correctamente.

**Comment by alvdomnun** [comment]
Investigación terminada, cierro la tarea.
