### ISSUE TITLE
Incidencia con Administración de Votaciones y Administración de Censos

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#31]
Existe un problema entre administración de votaciones y administración de censos. Los primeros no saben cómo obtener los datos que necesitan de los segundos, así que es necesaria una mediación para aclarar esta y posibles dudas que puedan surgir derivadas de la situación.

**Comment by JuanRubiio** [comment]
El coordinador de administración de votaciones me comenta que si pueden cambiar el nombre de una tabla question_options de la base de datos, a lo que se le responde que no, que los demás grupos están trabajando ya con esos esquemas y salvo por motivo de fuerza mayor no se cambiará nada.

**Comment by alvdomnun** [comment]
Ante la falta de respuestas por parte de los subgrupos respecto al avance de la incidencia, procedo a cerrarla. Si vuelve a aparecer la incidencia se creará una nueva.
