### ISSUE TITLE
DUDA: json desde almacenamiento

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/Integracion-EGC-G1#33]
Desde Recuento de votos no estamos seguros si dentro de la funcionalidad a implementar por parte del equipo de almacenamiento de votos está el responder con un json a una llamada restfull.

El json incluiría todos los votos de una poll, y la llamada resfull enviará la ip de la poll solicitada.

**Comment by alvdomnun** [comment]
Cierro la tarea al no tratarse de una concordante con el protocolo de resolución de dudas.
