### ISSUE TITLE
Autenticación y recuento de votos

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/Integracion-EGC-G1#34]
Desde recuento de votos no estamos seguros de cómo se va a gestionar la autenticación cuando recibamos una solicitud de resultados por nuestra api.

Nuestra propuesta es que el sistema que realice la llamada authentique previamente al usuario.

**Comment by alvdomnun** [comment]
Cierro la tarea al no seguir el esquema de resolución de dudas establecido.
