### ISSUE TITLE
Es necesario el almacenamiento de los resultados 

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/Integracion-EGC-G1#35]
Desde recuento de votos nos cabe la duda de si es necesario almacenar los resultados de una poll tras el recuento de los votos.

Nuestra resolución es que no debe ser necesario a priori dado que estos solo son usados para la visualización, aunque si podría mejorar el rendimiento que se guardaran una vez recontados los votos de una poll.

**Comment by alvdomnun** [comment]
Se cierra la tarea para crear una oficial del equipo de integración.
