### ISSUE TITLE
Cambios en la wiki: Establecimiento de un protocolo de resolución de dudas

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#38]
Redacción de un protocolo de resolución de dudas en la wiki, debido a que se están tratando de forma errónea por algunos de los subgrupos.

**Comment by Osem117** [comment]
Procedo a añadir y dar formato a un nuevo apartado sobre resolución de dudas y documentación en el espacio asignado para ello.

**Comment by alvdomnun** [comment]
Verificado por el resto de subgrupòs, cierro la tarea.
