### ISSUE TITLE
Cambios en la wiki: Aclaración sobre la gestión de cambios y tareas.

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#39]
Es necesario actualizar la gestión de cambios en la wiki del equipo, dado que hay subgrupos que están confundiéndose con el protocolo a seguir. También se debe actualizar la gestión de tareas para que reflejen la correlación con los commits.

**Comment by Osem117** [comment]
se ha añadido una aclaración sobre la forma de proceder a la hora de gestionar los cambios

**Comment by Osem117** [comment]
Se ha revisado la aclaración hecha. Cierro la tarea ya finalizada

**Comment by Osem117** [comment]
Queda reabierta la tarea a la espera de su revisión por parte de otro miembro a fin de verificar su correcta elaboración

**Comment by alvdomnun** [comment]
Verificada por el resto de subgrupos, cierro la tarea.
