### ISSUE TITLE
Revisión de correlación entre commits e issues

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#41]
Repasar cada Issue y commit para asegurarse de que siguen el formato establecido y se refleja el impacto de los segundos en los primeros. Esto incluye el formato de los documentos de los commits.

**Comment by SurielAido** [comment]
Se han puesto en Hecho las tareas finalizadas y se han cerrado sus issues. Todas las tareas con etiqueta Started que no estaban en la columna correspondiente se han movido de TO DO. Además, se ha creado la etiqueta "en discusión" para los cambios que aún no están aceptados.

**Comment by alvdomnun** [comment]
Se ha añadido la necesidad de añadir los asignados de repositorios externos en caso de ser una issue de una incidencia.

**Comment by SurielAido** [comment]
Se han asignado las issues a los commits (en forma de comentario, puesto que nosotros no podemos modificar el comentario que se hace al commitear)
