### ISSUE TITLE
Estandarización del puerto de acceso del servidor.

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#47]
Decisión del puerto estándar a usar por los subsistemas a la hora de acceder a la base de datos una vez montados en su contenedor Docker.

**Comment by miguemiguemigue** [comment]
Finalmente, se decide que los contenedores docker de cada subsistema recibirán las variables de entorno para configurar la URL y puerto de la base de datos del servidor. También se le añadirá de esta forma el usuario y contraseña de la bbdd.
