### ISSUE TITLE
Solicitud de cambio: Adición en la BD un campo para Censos

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#67]
Los miembros de Administración de Censos han solicitado añadir a la BD el siguiente campo:
-Un string que puede ser o no nulo cuyo contenido sea "abierto" o "cerrado".
-La función es averiguar si el censo está cerrado o no.
-En un primer momento no afecta a ningún otro grupo.

**Comment by alvdomnun** [comment]
Cambio aceptado, asignado a un miembro para que haga el script pertinente.

**Comment by SurielAido** [comment]
Cambio realizado. Se actualiza el la tabla en el repositorio de creación de tablas en la BD. Ahora censso cuenta con un enum con los valores 'Abierto' o 'Cerrado'. Pendiente de revisión.

**Comment by SurielAido** [comment]
Se ha eliminiado del repositorio el script subido por error. Se ha actualizado el script correspondiente con el campo requerido. A la espera de revisión.
