### ISSUE TITLE
Investigación sobre Travis

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#68]
Necesitamos averiguar cómo usar Travis para automatizar la subida y actualización de Dockerfiles en Dockerhub, compilándolo en local para que esto ocurra.

**Comment by Paula204** [comment]
Se sube la primera versión del documento de investigación

**Comment by alvdomnun** [comment]
Verificada la versión. Cierro la tarea.
efcf2bb22fd6ae8c0e056a05483d2b50b171f8c3
