### ISSUE TITLE
Investigación sobre Docker

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#7]
Investigación de Docker, cómo usarlo en el proyecto en nuestro equipo y recopilación de información.

**Comment by alvdomnun** [comment]
Se han reasignado las prioridades.

**Comment by miguemiguemigue** [comment]
Creado docker-compose con MySQL para el entorno de votaciones. Actualmente intentando crear un docker-compose con MySQL+PHP+Apache para Wordpress, está dando problemas con redirección de puertos.

**Comment by miguemiguemigue** [comment]
Finalmente, se ha creado un entorno docker con una imagen de WordPress y otra de MariaDB. Está subido a la rama develop de momento.
