### ISSUE TITLE
BUG: Errata en el documento del modelo de la base de datos.

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#80]
Se ha detectado una errata en el documento del modelo relacional. Faltaría un guión bajo en el atributo question_option. También se hace necesario comprobar que los nuevos campos están reflejados en el modelo.

**Comment by miguemiguemigue** [comment]
Se procede a actualizar el modelo relacional con respecto a la versión del script de votaciones del commit 8739f65
