### ISSUE TITLE
Cambio: Añadir dos campos nuevos a la clase Poll

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#82]
Desde Redes Sociales y las cabinas nos han pedido añadir dos atributos a la clase Poll:

-Uno primero de tipo Integer, que indique el número de gente que puede participar en ella.
-Un segundo de tipo Integer, que indique el número de gente que ya ha votado en ella.

No pueden ser nulos y su valor mínimo es 0.

**Comment by alvdomnun** [comment]
Se ha estudiado el cambio y se ha llegado a la siguiente conclusión:

-El primer campo es innecesario ya que se pueden obtener los datos deseados a partir del censo de la votación.
-Se añadirá el segundo campo para agilizar el proceso de trabajo.

**Comment by jorgegarciax2** [comment]
Desde redes sociales no consideramos que el campo sea innecesario puesto que desde el plugin de wordpress no es trivial realizar el calculo del censo. En censo no es un dato directo puesto que si se utiliza la opción de censo masivo tenemos que navegar hasta la tabla de usuarios comprobando la provincia de los mismos. La otra consulta si podría ser algo más directa, pero recuerdo que no somos un subsistema de Nvotes por lo que no es sencillo acceder al sistema de datos y realizar consultas en el mismo.

Cabe destacar que todos los equipos implicados han sido informados y están de acuerdo en dicho cambio.

**Comment by alvdomnun** [comment]
Hemos vuelto a pensar en la viabilidad del campo partiendo de la última argumentación y hemos decidido que para facilitar el acceso a esos datos desde Wordpress se añadirá también el segundo campo.

**Comment by jorgegarciax2** [comment]
Compartimos ese punto de vista y esperamos que estén incluidos próximamente para que los equipos puedan trabajar en ello. Gracias.

**Comment by SurielAido** [comment]
Se han añadido los campos requeridos y se ha commiteado la versión actualizada. Pendiente de revisón.
