### ISSUE TITLE
Integración de los plugins de Wordpress

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#84]
Preparación de los Wordpress recibidos por los subgrupos para poder subirlos en local y posteriormente en el servidor.

**Comment by Paula204** [comment]
Se ha empezado a investigar la preparación del wordpress pero todavía no se ha recibido nada de los grupos.

**Comment by SurielAido** [comment]
Se está trabajando en ello. Hemos avanzado en la primera parte para preparar el entorno para cuando recibamos los pluggins.

**Comment by Paula204** [comment]
Se ha conseguido integrar el pluggin de Gestión de Registro.

**Comment by Paula204** [comment]
Se han subido los pluggins de Redes Sociales y Generación Estática

**Comment by Paula204** [comment]
Subido el último pluggin que quedaba que era el de gestión de programas.
