### ISSUE TITLE
Integración continua en develop con Travis de un proyecto Python

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#86]
Preparación en local de una instancia de un proyecto Python. Una vez listo, se subirá a la rama de develop y se comprobará que Travis compila bien el proyecto subido en cada commit.

**Comment by miguemiguemigue** [comment]
El proyecto sobre el que se debe implementar Travis CI es el contenido en el siguiente enlace de la rama develop:
https://github.com/Proyecto-EGC-G1/Integracion-EGC-G1/tree/develop/Proyectos/servicio_despliegue

**Comment by miguemiguemigue** [comment]
Tarea realizada
