### ISSUE TITLE
Preparación y volcado de la BD en MySQL

### ISSUE THREAD

**Issue by alvdomnun** [Proyecto-EGC-G1/Integracion-EGC-G1#9]
Preparación de la BD de votaciones en MySQL y volcado del script de creación.

**Comment by miguemiguemigue** [comment]
Pendiente del correcto funcionamiento de la instancia MariaDB de Docker con los esquemas de WP y votaciones.

**Comment by alvdomnun** [comment]
Base de datos volcada en la imagen de MySQL y posteriormente añadida a Docker. Funciona correctamente. Cierro la tarea.
